**Try linear regression on same prediction data using tensorflow**

In [10]:
import numpy as np
import tensorflow as tf

data = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                 [69, 96, 70],[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                 [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                 [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float64')

target = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                   [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                   [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], 
                  dtype='float64')

In [11]:
data = tf.Variable(data)
target = tf.Variable(target)
print(f"target:- \n{target}\n")

target:- 
<tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>



In [12]:
d1 = np.random.rand(3, 2)
d1 = tf.Variable(d1)
print(f"d1:- \n{d1}\n")

d2 = np.random.randn(2)
d2 = tf.Variable(d2)
print(f"d2:- \n{d2}\n")

d1:- 
<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.94255381, 0.85248081],
       [0.92332556, 0.53742675],
       [0.54241155, 0.29987151]])>

d2:- 
<tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([-0.12877979, -1.46614272])>



In [15]:
def func(p):
    return p @ d1 + d2

In [16]:
prediction = func(data)
print(f"prediction:- \n{prediction}\n")

prediction:- 
[[153.86415722 109.66702436]
 [201.61060502 142.59494263]
 [237.05889631 162.10742102]
 [155.78393487 119.6914968 ]
 [191.51549505 129.93900781]
 [153.86415722 109.66702436]
 [201.61060502 142.59494263]
 [237.05889631 162.10742102]
 [155.78393487 119.6914968 ]
 [191.51549505 129.93900781]
 [153.86415722 109.66702436]
 [201.61060502 142.59494263]
 [237.05889631 162.10742102]
 [155.78393487 119.6914968 ]
 [191.51549505 129.93900781]]



In [17]:
def mse(p1, p2):
    return tf.reduce_mean(tf.square(p1-p2))
print(f"Mean Square Error:- \n{mse(prediction, target)}\n")

Mean Square Error:- 
7490.374797225369



In [19]:
ephoch = 50
for i in range(ephoch):
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(target, model(data))

    d11 = t.gradient(current_loss, d1)
    d21 = t.gradient(current_loss, d2)

    d1.assign_sub(1e-4 * d11)
    d2.assign_sub(1e-4 * d21)
        
    print(f"Epoch count: {i} \nLoss value: {current_loss.numpy()}\n")

Epoch count: 0 
Loss value: 72.88942321559388

Epoch count: 1 
Loss value: 66.27643699638254

Epoch count: 2 
Loss value: 60.48377537457205

Epoch count: 3 
Loss value: 55.3914457252916

Epoch count: 4 
Loss value: 50.901721906824726

Epoch count: 5 
Loss value: 46.933581585133126

Epoch count: 6 
Loss value: 43.41888607839875

Epoch count: 7 
Loss value: 40.29969203982964

Epoch count: 8 
Loss value: 37.526307820551764

Epoch count: 9 
Loss value: 35.05584781768304

Epoch count: 10 
Loss value: 32.85112653673856

Epoch count: 11 
Loss value: 30.879789898492632

Epoch count: 12 
Loss value: 29.11361665324865

Epoch count: 13 
Loss value: 27.527945241498394

Epoch count: 14 
Loss value: 26.101195827198627

Epoch count: 15 
Loss value: 24.81446651679613

Epoch count: 16 
Loss value: 23.651188838165137

Epoch count: 17 
Loss value: 22.59683156574981

Epoch count: 18 
Loss value: 21.63864468151485

Epoch count: 19 
Loss value: 20.765437122110985

Epoch count: 20 
Loss value: 19.96738327559