**Try linear regression just using numpy (without TensorFlow/Pytorch or other libraries)**

In [9]:
import numpy as np
from sklearn.linear_model import LinearRegression

data = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                 [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], 
                 [102, 43, 37], [69, 96, 70], [73, 67, 43],  [91, 88, 64], 
                 [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
print(data.shape)

(15, 3)


In [10]:
target = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                   [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                   [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], 
                  dtype='float32')

In [11]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.25, random_state=78)
reg = LinearRegression().fit(x_train, y_train)
print(f"reg:- \n{reg}\n")

reg:- 
LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)



In [12]:
print(f"reg.intercept_ :- \n{reg.intercept_}\n")
print(f"reg.coef_ :- \n{reg.coef_}\n")

reg.intercept_ :- 
[-1.3299713 -2.2399063]

reg.coef_ :- 
[[-0.38991737  0.8378035   0.71353155]
 [-0.28499374  0.7947048   0.9238994 ]]



In [13]:
y_predict = reg.predict(x_test)
print(f"y_predict:- \n{y_predict}\n")
print(f"y_test:- \n{y_test}\n")

y_predict:- 
[[ 82.58028  100.889244]
 [118.397705 133.04224 ]
 [ 57.020752  69.928444]
 [118.397705 133.04224 ]]

y_test:- 
[[ 81. 101.]
 [119. 133.]
 [ 56.  70.]
 [119. 133.]]



In [14]:
from sklearn import metrics

print(f"Mean Squared Error:- \n{metrics.mean_squared_error(y_test, y_predict)}\n")

Mean Squared Error:- 
0.5357102155685425

